services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: cloudvitals-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
