apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudvitals-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudvitals-backend
  template:
    metadata:
      labels:
        app: cloudvitals-backend
    spec:
      containers:
        - name: backend
          image: cloudvitals-monitoring-platform-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
